---


# Instalando o Vivaldi

- name: Instalando o Vivaldi
  zypper:
    name: vivaldi
    state: present
    force: yes
  become: true
  tags:
    - vivaldi
    - web

# Instalando o Google Chrome

- name: Instalando o Google Chrome
  zypper:
    name: google-chrome-stable
    state: present
    force: yes
  become: true
  tags:
    - chrome
    - web

# Instalando o Opera

- name: Instalando o Opera
  zypper:
    name: opera-stable
    state: present
    force: yes
  become: true
  tags:
    - opera
    - web
